<?xml version="1.0" encoding="utf-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="name radius thickness positionX positionY positionZ">
        <link name="${name}_link">
            <!--           ignoring inertia for rviz-->
            <!--           <inertial>-->
            <!--               <mass value ="2"/>-->
            <!--               <origin rpy ="1.57 0 0" xyz="0 0 0"/>-->
            <!--               &lt;!&ndash; <inertia ixx="200" ixy ="0" ixz="0" iyy="0.1" iyz="0" izz="0.01"/> &ndash;&gt;-->
            <!--               <inertia ixx="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}" ixy ="0" ixz="0"-->
            <!--                        iyy="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}"-->
            <!--                        iyz="0"-->
            <!--                        izz="${0.5 * 8 * radius * radius}"/>-->
            <!--           </inertial>-->

            <!--       adding visual effect-->
            <visual>
                <origin rpy="1.57 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${thickness}" radius="${radius}"/>
                </geometry>
            </visual>

            <!--           ignoring collision for rviz -->
            <!-- <collision name="$(name)_collision"> -->
            <!--           <collision>-->
            <!--               <origin rpy="1.57 0 0" xyz="0 0 0"/>-->
            <!--               <geometry>-->
            <!--                   <cylinder length="${thickness}" radius="${radius + 0.001}"/>-->
            <!--               </geometry>-->
            <!--           </collision>-->

        </link>
        <joint name="${name}_joint" type="continuous">
            <origin rpy="0 0 0" xyz="${positionX} ${positionY} ${positionZ}"/>
            <child link="${name}_link"/>
            <parent link="base_link"/>
            <axis rpy="0 0 0" xyz="0 1 0"/>
            <!--          ignoring dynamic parameters for rviz-->
            <!--           <limit effort="10000" velocity="1000"/>-->
            <!--           <joint_properties damping="0" friction="0"/>-->
        </joint>
    </xacro:macro>
</robot>