<?xml version="1.0" encoding="UTF-8" ?>
<!--this file is to define a robot base with four wheels and the robot is axis symmertric about its centre-->
<robot name="prototype3" xmlns:xacro="http://wwww.ros.org/wiki/xacro">
<!--    length of robot chassis-->
    <xacro:property name="robot_length" value="1.0"/>
<!--    width of robot chassis-->
    <xacro:property name="robot_width" value="0.8"/>
<!--    height of robot chassis-->
    <xacro:property name="robot_height" value="0.6"/>
<!--    distance between axis of front wheel to front surface-->
    <xacro:property name="front_wheel_horizontal_distance" value="0.1"/>
<!--    distance between axis of front wheel to bottom surface -->
    <xacro:property name="front_wheel_vertical_distance" value="0.1"/>
<!--    distance between front wheel centre to side surface-->
    <xacro:property name="front_wheel_offset" value="0.08"/>
<!--    radius of front wheel-->
    <xacro:property name="front_wheel_radius" value="0.15"/>
<!--    front wheel thickness-->
    <xacro:property name="front_wheel_thickness" value="0.08"/>
    <!--    distance between axis of rear wheel to front surface-->
    <xacro:property name="rear_wheel_horizontal_distance" value="0.1"/>
    <!--    distance between axis of rear wheel to bottom surface -->
    <xacro:property name="rear_wheel_vertical_distance" value="0.1"/>
    <!--    distance between rear wheel centre to side surface-->
    <xacro:property name="rear_wheel_offset" value="0.08"/>
<!--    radius of rear wheel-->
    <xacro:property name="rear_wheel_radius" value="0.15"/>
    <!--    rear wheel thickness-->
    <xacro:property name="rear_wheel_thickness" value="0.08"/>

<!--    There is no need to touch the rest code-->
<!--    for front wheels only-->
    <xacro:property name="front_positionX" value="${1/2*robot_length-front_wheel_horizontal_distance}"/>
    <xacro:property name="front_positionY" value="${1/2*robot_width+front_wheel_offset}"/>
    <xacro:property name="front_positionZ" value="${1/2*robot_height-front_wheel_vertical_distance}"/>

<!--    for back wheels only-->
    <xacro:property name="rear_positionX" value="${-1/2*robot_length+rear_wheel_horizontal_distance}"/>
    <xacro:property name="rear_positionY" value="${1/2*robot_width+rear_wheel_offset}"/>
    <xacro:property name="rear_positionZ" value="${1/2*robot_height-rear_wheel_vertical_distance}"/>


    <!--    adding the chassis-->
    <xacro:include filename="$(find mobileman_navigation)/urdf/chassis_flexible.xacro"/>
    <xacro:chassis length="${robot_length}" width="${robot_width}" height="${robot_height}"/>
<!--adding wheels-->
<!--    x direction is front, y direction is left, z direction is upward-->
    <xacro:include filename="$(find mobileman_navigation)/urdf/configurable_wheels.xacro"/>
    <xacro:wheel name="front_left" radius="${front_wheel_radius}" thickness="${front_wheel_thickness}" positionX="${front_positionX}" positionY="${front_positionY}" positionZ="${front_positionZ}"/>
    <xacro:wheel name="front_right" radius="${front_wheel_radius}" thickness="${front_wheel_thickness}" positionX="${front_positionX}" positionY="${front_positionY*(-1)}" positionZ="${front_positionZ}"/>
    <xacro:wheel name="rear_left" radius="${rear_wheel_radius}" thickness="${rear_wheel_thickness}" positionX="${rear_positionX}" positionY="${rear_positionY}" positionZ="${rear_positionZ}"/>
    <xacro:wheel name="rear_right" radius="${rear_wheel_radius}" thickness="${rear_wheel_thickness}" positionX="${rear_positionX}" positionY="${rear_positionY*(-1)}" positionZ="${rear_positionZ}"/>

<!--    adding base_footprint-->
    <xacro:include filename="$(find mobileman_navigation)/urdf/configurable_wheels.xacro"/>
    <xacro:include filename="$(find mobileman_navigation)/urdf/base_footprint.xacro"/>
<!--    base foot_print length-->
    <xacro:property name="footprint_length" value="${front_positionX - rear_positionX + front_wheel_radius +  rear_wheel_radius + 0.05}"/>
<!--base footprint width, determined by the larger edge-to-edge distance of front wheels vs rear wheels-->
    <xacro:if value="${(front_positionY + 1/2 * front_wheel_thickness)>=(rear_positionY + 1/2 * rear_wheel_thickness)}">
    <xacro:property name="footprint_width" value="${2 * front_positionY +  front_wheel_thickness + 0.05}"/>
    </xacro:if>
    <xacro:unless value="${(front_positionY + 1/2 * front_wheel_thickness)>=(rear_positionY + 1/2 * rear_wheel_thickness)}">
      <xacro:property name="footprint_width" value="${2 * rear_positionY + rear_wheel_thickness + 0.05}"/>
    </xacro:unless>
<!--    the position of footprint, locationed at the lowest point of the vehicle-->
  <xacro:property name="footprint_positionZ" value="${front_positionZ - front_wheel_radius}"/>

  <xacro:base_footprint length ="${footprint_length}" width="${footprint_width}" positionZ="${footprint_positionZ}"/>

</robot>