# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: photoneo_3d_scanner
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - fork_rotational_joint
    - fork_linear_joint
    - photoneo_3d_scanner_joint
  sim_control_mode: 1 # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

photoneo_3d_scanner_controller:
  type: position_controllers/JointPositionController
  joints:
    - fork_rotational_joint
    - fork_linear_joint
    - photoneo_3d_scanner_joint
  gains:
    fork_rotational_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fork_linear_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    photoneo_3d_scanner_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

controller_list:
  - name: photoneo_3d_scanner_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - fork_rotational_joint
    - fork_linear_joint
    - photoneo_3d_scanner_joint
