#! /usr/bin/env python
# @file savemap.py
# @brief this file is used to save the map generated by cartographer
# @author Bingbingli Bingbingli@ntu.edu.sg
# @version 0.1
from __future__ import print_function

from sys import argv
import rospy
from cartographer_ros_msgs.srv import *
from rospy.timer import sleep


def save_map(filename):
    rospy.wait_for_service('finish_trajectory')
    try:
        finishTrajectory = rospy.ServiceProxy('finish_trajectory', FinishTrajectory)
        rosp = finishTrajectory(0)        
    except rospy.ServiceException as e:
        print("Finish Trajectory service call failed: %s"%e)
        sys.exit(1)
    sleep(1)
    try: 
        writeState = rospy.ServiceProxy('write_state',WriteState)
        request = WriteStateRequest(filename,True)
        rosp = writeState()
    except rospy.ServiceException as e:
        print("write state service call failed: %s"%e)
        sys.exit(1)
    print ("map saved to %s"%filename)
def usage():
    return "Usage: %s [filename.pbstream]"%sys.argv[0]

if __name__ == "__main__":
    if len(sys.argv) == 2:
        save_map(sys.argv[1])
    else:
        print(usage())
        sys.exit(1)
