<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="rear_link_wheel" params="name radius">
    <link name="rear_${name}_link">
      <inertial>
        <mass value="2" />
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <!-- <inertia ixx="200" ixy ="0" ixz="0" iyy="0.1" iyz="0" izz="0.01"/> -->
        <inertia ixx="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}" ixy="0" ixz="0" iyy="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}" iyz="0" izz="${0.5 * 8 * radius * radius}" />
      </inertial>

      <!-- <visual name="$(name)_visual"> -->
      <visual>
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.01" radius="${radius}" />
        </geometry>
      </visual>

      <!-- <collision name="$(name)_collision"> -->
      <collision>
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.085" radius="${radius + 0.001}" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="dummy_wheel" params="name radius">
    <link name="rear_${name}_dummy_link">
      <inertial>
        <mass value="8" />
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <inertia ixx="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}" ixy="0" ixz="0" iyy="${1/12 * 8 * (3 * radius * radius + 0.085 * 0.085)}" iyz="0" izz="${0.5 * 8 * radius * radius}" />
      </inertial>

      <!-- <visual name="$(name)_visual"> -->
      <visual>
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.001" radius="${radius}" />
        </geometry>
      </visual>

      <!-- <collision name="$(name)_collision"> -->
      <collision>
        <origin rpy="1.57 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="0.085" radius="${radius + 0.01}" />
        </geometry>
        <surface>
          <contact>
            <ode>
              <kp>1e15</kp>
              <kd>1e13</kd>
            </ode>
          </contact>
        </surface>
      </collision>
    </link>
  </xacro:macro>
  <xacro:macro name="rear_joint_wheel" params="name origin_xyz">
    <joint name="${name}_joint" type="fixed">
      <origin rpy="0 0 0" xyz="${origin_xyz}" />
      <child link="${name}_link" />
      <parent link="${base_link}" />
      <axis rpy="0 0 0" xyz="0 1 0" />
      <limit effort="10000" velocity="1000" />
      <joint_properties damping="0" friction="0" />
    </joint>
  </xacro:macro>
</robot>