subscribers:
  - name:        "Default input"
    topic:       "cmd_line/cmd_vel"
    timeout:     0.1
    priority:    6
    short_desc:  "The default cmd_vel, controllers unaware that we are multiplexing cmd_vel should come here"

  - name:        "Navigation stack"
    topic:       "move_base/cmd_vel"
    timeout:     0.5
    priority:    5
    short_desc:  "Navigation stack controller"

  - name:        "Web application"
    topic:       "web/cmd_vel"
    timeout:     0.3
    priority:    8

  - name:        "joystick operation operation"
    topic:       "joy/cmd_vel"
    timeout:     0.1
    priority:    7
publisher:       "prototype2/cmd_vel"
