---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bingbing.
--- DateTime: 5/17/21 2:27 PM
---
include "mobileman.lua"
TRAJECTORY_BUILDER.pure_localization = true
TRAJECTORY_BUILDER.pure_localization_trimmer = {
    max_submaps_to_keep = 3 ,
}
POSE_GRAPH.optimize_every_n_nodes = 20
return options